version: "3.9"
   
services:
    postgres:
        image: "postgres:9.6.21-alpine"
        environment:
          POSTGRES_USER: guest
          POSTGRES_PASSWORD: guest
          POSTGRES_DB: test_db
        ports:
          - 2345:5432